### ISSUE TITLE
当创建数据时就设置Group展开的话，子列表并不会展示，并且点击Group项目会导致Crash

### ISSUE THREAD

**Issue by kelv1nq1an** [zaihuishou/ExpandableRecyclerview#19]
以下内容是我download该项目并运行时发生的
```
zaihuishou.com.expandablerecyclerview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: zaihuishou.com.expandablerecyclerview, PID: 16410
                                                                                       java.lang.IndexOutOfBoundsException: Index: 10, Size: 2
                                                                                           at java.util.ArrayList.get(ArrayList.java:411)
                                                                                           at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.collapseParentListItem(BaseExpandableAdapter.java:175)
                                                                                           at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.onParentListItemCollapsed(BaseExpandableAdapter.java:142)
                                                                                           at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.collapseView(AbstractExpandableAdapterItem.java:119)
                                                                                           at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.doExpandOrUnexpand(AbstractExpandableAdapterItem.java:130)
                                                                                           at zaihuishou.com.expandablerecyclerview.CompanyItem.access$000(CompanyItem.java:12)
                                                                                           at zaihuishou.com.expandablerecyclerview.CompanyItem$1.onClick(CompanyItem.java:31)
                                                                                           at android.view.View.performClick(View.java:5639)
                                                                                           at android.view.View$PerformClick.run(View.java:22391)
                                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6088)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by zaihuishou** [comment]
产生这个错误的原因是jcenter的代码不是最新的，你如果把demo的代码运行下就知道已经解决你的问题

**Comment by zaihuishou** [comment]
可以使用gradle了，我已经更新了
