### ISSUE TITLE
运行demo崩溃了

### ISSUE THREAD

**Issue by ghost** [zaihuishou/ExpandableRecyclerview#23]
FATAL EXCEPTION: main
                                                                                       java.lang.IndexOutOfBoundsException: Invalid index 10, size is 2
                                                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
                                                                                           at java.util.ArrayList.get(ArrayList.java:304)
                                                                                           at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.collapseParentListItem(BaseExpandableAdapter.java:226)
                                                                                           at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.onParentListItemCollapsed(BaseExpandableAdapter.java:194)
                                                                                           at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.collapseView(AbstractExpandableAdapterItem.java:119)
                                                                                           at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.doExpandOrUnexpand(AbstractExpandableAdapterItem.java:130)
                                                                                           at zaihuishou.com.expandablerecyclerview.CompanyItem.access$000(CompanyItem.java:12)
                                                                                           at zaihuishou.com.expandablerecyclerview.CompanyItem$1.onClick(CompanyItem.java:31)
                                                                                           at android.view.View.performClick(View.java:4207)
                                                                                           at android.view.View$PerformClick.run(View.java:17372)
                                                                                           at android.os.Handler.handleCallback(Handler.java:725)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5082)
                                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by zaihuishou** [comment]
推荐用airbnb的[Epoxy](https://github.com/airbnb/epoxy)
