### ISSUE TITLE
数组越界崩溃

### ISSUE THREAD

**Issue by NFLeo** [zaihuishou/ExpandableRecyclerview#24]
频繁数据越界崩溃

**Comment by zaihuishou** [comment]
能贴点具体日志吗？

**Comment by NFLeo** [comment]
你几个item多点几次就有了，很容易重现的

**Comment by MissMyDearBear** [comment]
我来贴吧
 Process: zaihuishou.com.expandablerecyclerview, PID: 4349
                                                                                     java.lang.IndexOutOfBoundsException: Invalid index 12, size is 12
                                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
                                                                                         at java.util.ArrayList.get(ArrayList.java:313)
                                                                                         at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.collapseParentListItem(BaseExpandableAdapter.java:226)
                                                                                         at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.onParentListItemCollapsed(BaseExpandableAdapter.java:194)
                                                                                         at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.collapseView(AbstractExpandableAdapterItem.java:119)
                                                                                         at zaihuishou.com.expandablerecyclerview.DepartmentItem.onClick(DepartmentItem.java:75)

**Comment by Hitexroid** [comment]
@MissMyDearBear It's my problem too !
@zaihuishou please help .

**Comment by zaihuishou** [comment]
这个库我可能不在维护了，你可以用[Epoxy](https://github.com/airbnb/epoxy)代替，这个库很牛逼
