### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 12, size is 12

### ISSUE THREAD

**Issue by Hitexroid** [zaihuishou/ExpandableRecyclerview#29]
What's the problem ?

>  java.lang.IndexOutOfBoundsException: Invalid index 12, size is 12
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.collapseParentListItem(BaseExpandableAdapter.java:226)
                      at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.onParentListItemCollapsed(BaseExpandableAdapter.java:194)
                      at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.collapseView(AbstractExpandableAdapterItem.java:119)
                      at com.application.admin.Adapters.ExpandablesAdapter.FieldItem.onClick(FieldItem.java:77)
                      at android.view.View.performClick(View.java:5280)
                      at android.view.View$PerformClick.run(View.java:21239)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:234)
                      at android.app.ActivityThread.main(ActivityThread.java:5526)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by zaihuishou** [comment]
You can use [epoxy](https://github.com/airbnb/epoxy)
