### ISSUE TITLE
我直接将demo下下来跑 运行崩溃呀

### ISSUE THREAD

**Issue by zzzsssbo** [zaihuishou/ExpandableRecyclerview#31]
08-23 17:29:30.199 1775-1775/zaihuishou.com.expandablerecyclerview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: zaihuishou.com.expandablerecyclerview, PID: 1775
    java.lang.IndexOutOfBoundsException: Invalid index 10, size is 2
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.collapseParentListItem(BaseExpandableAdapter.java:226)
        at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.onParentListItemCollapsed(BaseExpandableAdapter.java:194)
        at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.collapseView(AbstractExpandableAdapterItem.java:119)
        at com.zaihuishou.expandablerecycleradapter.viewholder.AbstractExpandableAdapterItem.doExpandOrUnexpand(AbstractExpandableAdapterItem.java:130)
        at zaihuishou.com.expandablerecyclerview.CompanyItem.access$000(CompanyItem.java:12)
        at zaihuishou.com.expandablerecyclerview.CompanyItem$1.onClick(CompanyItem.java:31)
        at android.view.View.performClick(View.java:5215)
        at android.view.View$PerformClick.run(View.java:21196)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by mayangyang-github** [comment]
我也是... 很难过

**Comment by zaihuishou** [comment]
不好意思，很久很久没登陆，此项目很久不维护啦，请使用更优秀的库：[epoxy](https://github.com/zaihuishou/epoxy)
