### ISSUE TITLE
运行你demo的时候有一个异常

### ISSUE THREAD

**Issue by maddockFeng** [zaihuishou/ExpandableRecyclerview#4]
08-01 18:14:07.811 30989-30989/zaihuishou.com.expandablerecyclerview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: zaihuishou.com.expandablerecyclerview, PID: 30989
                                                                                       android.view.InflateException: Binary XML file line #2: Error inflating class android.widget.RelativeLayout
                                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                                           at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                           at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:472)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                                           at com.zaihuishou.expandablerecycleradapter.viewholder.BaseAdapterItem.<init>(BaseAdapterItem.java:0)
                                                                                           at com.zaihuishou.expandablerecycleradapter.adapter.BaseExpandableAdapter.onCreateViewHolder(BaseExpandableAdapter.java:405)
                                                                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                           at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1092)
                                                                                           at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:802)
                                                                                           at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:816)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                           at android.view.View.layout(View.java:14828)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2078)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1835)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1091)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5700)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                        at android.view.Choreograp

**Comment by zaihuishou** [comment]
如果你是继承AbstractExpandableAdapterItem 的，在onBindViews，onUpdateViews必须调用super。具体原因可以多给点日志或者给个测试的demo让我看看嘛？

**Comment by maddockFeng** [comment]
我只是运行了你的demo，没有做任何改动啊，很奇怪

**Comment by zaihuishou** [comment]
不会啊，我这都可以运行啊。你查看下日志，具体错误，好好找下。

**Comment by maddockFeng** [comment]
在4.4.4版本上会出错，在5.1的手机上正常

**Comment by zaihuishou** [comment]
我找到是什么错误了(水波纹效果没做版本适配)，改了马上提交，你等会再试下。

**Comment by maddockFeng** [comment]
现在不会奔溃了，但是点击列表不会展开，只有箭头方向会变化

**Comment by zaihuishou** [comment]
应该是createCompany方法里面注释了导致公司里面没有部门了，所以无法展开
